### ISSUE TITLE
ChewChat IRC server option

### ISSUE THREAD

**Issue by soarn** [Chewbotcca/SpamBeGone#4]
1) If a user mentions all Notifico (Not-XXX) bots in one messge, then they are G-Lined. (Channel Specific (Add channel customization))

2) If a user mentions more than 3 users with a hostmask of `*!*@network/bots/XXXX/XXXXX` in one message, they are G-Lined

3) If a user mentions more than 3 network staff in a message, they are G-Lined

4) If a user mentions multiple other users in on one message on a channel, and those other users are `+o` or higher, they are G-Lined

**Comment by Chew** [comment]
1) I probably won't add a "instant punish" option based on nicknames until I add a way to deduce mentions from normal text to see if that message is really spam.
2) see point 1
3) This just isn't possible without seeing who is Network staff. Also see point 1
4) This is possible but doesn't have a use, what if someone just wants to be annoying and mention ops because they really have a question?

**Comment by Chew** [comment]
Also geez, what is your obsession with G-lining, it isn't even implemented yet and when it is, it will be optional.

**Comment by soarn** [comment]
I used G-Lines because we have two servers but then again, they're only connected to one.

So, if they are just spamming once, K-Line, if they rejoin and do it again, G-Line.
>Implement a way to check if a user has been punished before

**Comment by Chew** [comment]
Feel free to make "Implement a way to check if a user has been punished before" an issue, but this is a universal bot, able to work on any server that supports kill, k-line, g-line, etc, and I have to make config options universal as well.
